//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockEmbeddingModelConfiguration) DeepCopyInto(out *BedrockEmbeddingModelConfiguration) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = new(int32)
		**out = **in
	}
	if in.EmbeddingDataType != nil {
		in, out := &in.EmbeddingDataType, &out.EmbeddingDataType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockEmbeddingModelConfiguration.
func (in *BedrockEmbeddingModelConfiguration) DeepCopy() *BedrockEmbeddingModelConfiguration {
	if in == nil {
		return nil
	}
	out := new(BedrockEmbeddingModelConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingModelConfiguration) DeepCopyInto(out *EmbeddingModelConfiguration) {
	*out = *in
	if in.BedrockEmbeddingModelConfiguration != nil {
		in, out := &in.BedrockEmbeddingModelConfiguration, &out.BedrockEmbeddingModelConfiguration
		*out = new(BedrockEmbeddingModelConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingModelConfiguration.
func (in *EmbeddingModelConfiguration) DeepCopy() *EmbeddingModelConfiguration {
	if in == nil {
		return nil
	}
	out := new(EmbeddingModelConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBase) DeepCopyInto(out *KnowledgeBase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBase.
func (in *KnowledgeBase) DeepCopy() *KnowledgeBase {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseConfiguration) DeepCopyInto(out *KnowledgeBaseConfiguration) {
	*out = *in
	if in.VectorKnowledgeBaseConfiguration != nil {
		in, out := &in.VectorKnowledgeBaseConfiguration, &out.VectorKnowledgeBaseConfiguration
		*out = new(VectorKnowledgeBaseConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseConfiguration.
func (in *KnowledgeBaseConfiguration) DeepCopy() *KnowledgeBaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseList) DeepCopyInto(out *KnowledgeBaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnowledgeBase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseList.
func (in *KnowledgeBaseList) DeepCopy() *KnowledgeBaseList {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseObservation) DeepCopyInto(out *KnowledgeBaseObservation) {
	*out = *in
	if in.KnowledgeBaseArn != nil {
		in, out := &in.KnowledgeBaseArn, &out.KnowledgeBaseArn
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseId != nil {
		in, out := &in.KnowledgeBaseId, &out.KnowledgeBaseId
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureReasons != nil {
		in, out := &in.FailureReasons, &out.FailureReasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseObservation.
func (in *KnowledgeBaseObservation) DeepCopy() *KnowledgeBaseObservation {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseParameters) DeepCopyInto(out *KnowledgeBaseParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RoleArn != nil {
		in, out := &in.RoleArn, &out.RoleArn
		*out = new(string)
		**out = **in
	}
	if in.KnowledgeBaseConfiguration != nil {
		in, out := &in.KnowledgeBaseConfiguration, &out.KnowledgeBaseConfiguration
		*out = new(KnowledgeBaseConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.StorageConfiguration != nil {
		in, out := &in.StorageConfiguration, &out.StorageConfiguration
		*out = new(StorageConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClientToken != nil {
		in, out := &in.ClientToken, &out.ClientToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseParameters.
func (in *KnowledgeBaseParameters) DeepCopy() *KnowledgeBaseParameters {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseSpec) DeepCopyInto(out *KnowledgeBaseSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseSpec.
func (in *KnowledgeBaseSpec) DeepCopy() *KnowledgeBaseSpec {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseStatus) DeepCopyInto(out *KnowledgeBaseStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseStatus.
func (in *KnowledgeBaseStatus) DeepCopy() *KnowledgeBaseStatus {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchServerlessConfiguration) DeepCopyInto(out *OpenSearchServerlessConfiguration) {
	*out = *in
	if in.CollectionArn != nil {
		in, out := &in.CollectionArn, &out.CollectionArn
		*out = new(string)
		**out = **in
	}
	if in.FieldMapping != nil {
		in, out := &in.FieldMapping, &out.FieldMapping
		*out = new(OpenSearchServerlessFieldMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.VectorIndexName != nil {
		in, out := &in.VectorIndexName, &out.VectorIndexName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchServerlessConfiguration.
func (in *OpenSearchServerlessConfiguration) DeepCopy() *OpenSearchServerlessConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenSearchServerlessConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchServerlessFieldMapping) DeepCopyInto(out *OpenSearchServerlessFieldMapping) {
	*out = *in
	if in.MetadataField != nil {
		in, out := &in.MetadataField, &out.MetadataField
		*out = new(string)
		**out = **in
	}
	if in.TextField != nil {
		in, out := &in.TextField, &out.TextField
		*out = new(string)
		**out = **in
	}
	if in.VectorField != nil {
		in, out := &in.VectorField, &out.VectorField
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchServerlessFieldMapping.
func (in *OpenSearchServerlessFieldMapping) DeepCopy() *OpenSearchServerlessFieldMapping {
	if in == nil {
		return nil
	}
	out := new(OpenSearchServerlessFieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PineconeConfiguration) DeepCopyInto(out *PineconeConfiguration) {
	*out = *in
	if in.ConnectionString != nil {
		in, out := &in.ConnectionString, &out.ConnectionString
		*out = new(string)
		**out = **in
	}
	if in.CredentialsSecretArn != nil {
		in, out := &in.CredentialsSecretArn, &out.CredentialsSecretArn
		*out = new(string)
		**out = **in
	}
	if in.FieldMapping != nil {
		in, out := &in.FieldMapping, &out.FieldMapping
		*out = new(PineconeFieldMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PineconeConfiguration.
func (in *PineconeConfiguration) DeepCopy() *PineconeConfiguration {
	if in == nil {
		return nil
	}
	out := new(PineconeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PineconeFieldMapping) DeepCopyInto(out *PineconeFieldMapping) {
	*out = *in
	if in.MetadataField != nil {
		in, out := &in.MetadataField, &out.MetadataField
		*out = new(string)
		**out = **in
	}
	if in.TextField != nil {
		in, out := &in.TextField, &out.TextField
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PineconeFieldMapping.
func (in *PineconeFieldMapping) DeepCopy() *PineconeFieldMapping {
	if in == nil {
		return nil
	}
	out := new(PineconeFieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3VectorsConfiguration) DeepCopyInto(out *S3VectorsConfiguration) {
	*out = *in
	if in.IndexArn != nil {
		in, out := &in.IndexArn, &out.IndexArn
		*out = new(string)
		**out = **in
	}
	if in.IndexName != nil {
		in, out := &in.IndexName, &out.IndexName
		*out = new(string)
		**out = **in
	}
	if in.VectorBucketArn != nil {
		in, out := &in.VectorBucketArn, &out.VectorBucketArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3VectorsConfiguration.
func (in *S3VectorsConfiguration) DeepCopy() *S3VectorsConfiguration {
	if in == nil {
		return nil
	}
	out := new(S3VectorsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfiguration) DeepCopyInto(out *StorageConfiguration) {
	*out = *in
	if in.S3VectorsConfiguration != nil {
		in, out := &in.S3VectorsConfiguration, &out.S3VectorsConfiguration
		*out = new(S3VectorsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.OpensearchServerlessConfiguration != nil {
		in, out := &in.OpensearchServerlessConfiguration, &out.OpensearchServerlessConfiguration
		*out = new(OpenSearchServerlessConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.PineconeConfiguration != nil {
		in, out := &in.PineconeConfiguration, &out.PineconeConfiguration
		*out = new(PineconeConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfiguration.
func (in *StorageConfiguration) DeepCopy() *StorageConfiguration {
	if in == nil {
		return nil
	}
	out := new(StorageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorKnowledgeBaseConfiguration) DeepCopyInto(out *VectorKnowledgeBaseConfiguration) {
	*out = *in
	if in.EmbeddingModelArn != nil {
		in, out := &in.EmbeddingModelArn, &out.EmbeddingModelArn
		*out = new(string)
		**out = **in
	}
	if in.EmbeddingModelConfiguration != nil {
		in, out := &in.EmbeddingModelConfiguration, &out.EmbeddingModelConfiguration
		*out = new(EmbeddingModelConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorKnowledgeBaseConfiguration.
func (in *VectorKnowledgeBaseConfiguration) DeepCopy() *VectorKnowledgeBaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(VectorKnowledgeBaseConfiguration)
	in.DeepCopyInto(out)
	return out
}
